# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Andrew Nave
tagline: 
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'My life has been devoted to improving life with high quality food and music. I have 10 years of experience in the foodservice industry, where my family has served gourmet popcorn to countless wonderful customers in the Syracuse area for 3 generations. I apply that focus on quality to music, where I write and perform music for all.'

#sidebar links
email: hello@acnave.com
phone:
website: acnave.com #do not add http://
linkedin: acnave
github: acnave
twitter: 
#Update all the sections by editing the files inside _data folder.

# Tracker
#analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
